export const LocationOptions = [
    { value: "Overseas", label: "Overseas" },
    { value: "Andaman &amp; Nicobar - Andaman", label: "Andaman &amp; Nicobar - Andaman" },
    { value: "Andaman &amp; Nicobar - Nicobar", label: "Andaman &amp; Nicobar - Nicobar" },
    { value: "Andhra Pradesh - Adilabad", label: "Andhra Pradesh - Adilabad" },
    { value: "Andhra Pradesh - Anantpur", label: "Andhra Pradesh - Anantpur" },
    { value: "Andhra Pradesh - Chittor", label: "Andhra Pradesh - Chittor" },
    { value: "Andhra Pradesh - Cuddapah", label: "Andhra Pradesh - Cuddapah" },
    { value: "Andhra Pradesh - east Godavari", label: "Andhra Pradesh - east Godavari" },
    { value: "Andhra Pradesh - Guntur", label: "Andhra Pradesh - Guntur" },
    { value: "Andhra Pradesh - Hyderabad Urban", label: "Andhra Pradesh - Hyderabad Urban" },
    { value: "Andhra Pradesh - Karim Nagar", label: "Andhra Pradesh - Karim Nagar" },
    { value: "Andhra Pradesh - Khammam", label: "Andhra Pradesh - Khammam" },
    { value: "Andhra Pradesh - Krishna", label: "Andhra Pradesh - Krishna" },
    { value: "Andhra Pradesh - Kurnool", label: "Andhra Pradesh - Kurnool" },
    { value: "Andhra Pradesh - Medak", label: "Andhra Pradesh - Medak" },
    { value: "Andhra Pradesh - Mehboobnagar", label: "Andhra Pradesh - Mehboobnagar" },
    { value: "Andhra Pradesh - Nalgonda", label: "Andhra Pradesh - Nalgonda" },
    { value: "Andhra Pradesh - Nellore", label: "Andhra Pradesh - Nellore" },
    { value: "Andhra Pradesh - Nizamabad", label: "Andhra Pradesh - Nizamabad" },
    { value: "Andhra Pradesh - Prakasam", label: "Andhra Pradesh - Prakasam" },
    { value: "Andhra Pradesh - Ranga Reddy", label: "Andhra Pradesh - Ranga Reddy" },
    { value: "Andhra Pradesh - Srikakulam", label: "Andhra Pradesh - Srikakulam" },
    { value: "Andhra Pradesh - Vishakapatnam", label: "Andhra Pradesh - Vishakapatnam" },
    { value: "Andhra Pradesh - Vizianagaram", label: "Andhra Pradesh - Vizianagaram" },
    { value: "Andhra Pradesh - Warangal", label: "Andhra Pradesh - Warangal" },
    { value: "Andhra Pradesh - West Godavari", label: "Andhra Pradesh - West Godavari" },
    { value: "Arunachal Pradesh - Alog( West Siang )", label: "Arunachal Pradesh - Alog( West Siang )" },
    { value: "Arunachal Pradesh - Bomdila", label: "Arunachal Pradesh - Bomdila" },
    { value: "Arunachal Pradesh - Changalang", label: "Arunachal Pradesh - Changalang" },
    { value: "Arunachal Pradesh - Daporijo", label: "Arunachal Pradesh - Daporijo" },
    { value: "Arunachal Pradesh - Diban Valley( Anini Valley)", label: "Arunachal Pradesh - Diban Valley( Anini Valley)" },
    { value: "Arunachal Pradesh - Dibang Valley", label: "Arunachal Pradesh - Dibang Valley" },
    { value: "Arunachal Pradesh - East Kameng Seppa", label: "Arunachal Pradesh - East Kameng Seppa" },
    { value: "Arunachal Pradesh - East Siang(Passighat)", label: "Arunachal Pradesh - East Siang(Passighat)" },
    { value: "Arunachal Pradesh - Itanagar", label: "Arunachal Pradesh - Itanagar" },
    { value: "Arunachal Pradesh - Khonsa", label: "Arunachal Pradesh - Khonsa" },
    { value: "Arunachal Pradesh - Lohit(Tezu)", label: "Arunachal Pradesh - Lohit(Tezu)" },
    { value: "Arunachal Pradesh - Lower Subansiri(Ziro)", label: "Arunachal Pradesh - Lower Subansiri(Ziro)" },
    { value: "Arunachal Pradesh - Roin", label: "Arunachal Pradesh - Roin" },
    { value: "Arunachal Pradesh - Tawang", label: "Arunachal Pradesh - Tawang" },
    { value: "Assam - Barpeta", label: "Assam - Barpeta" },
    { value: "Assam - Bongaigaon", label: "Assam - Bongaigaon" },
    { value: "Assam - Cachar", label: "Assam - Cachar" },
    { value: "Assam - Darrang", label: "Assam - Darrang" },
    { value: "Assam - Dhemaji", label: "Assam - Dhemaji" },
    { value: "Assam - Dhubri", label: "Assam - Dhubri" },
    { value: "Assam - Dibrugarh", label: "Assam - Dibrugarh" },
    { value: "Assam - Goalpara", label: "Assam - Goalpara" },
    { value: "Assam - Golaghat", label: "Assam - Golaghat" },
    { value: "Assam - Hailakandi", label: "Assam - Hailakandi" },
    { value: "Assam - Jorhat", label: "Assam - Jorhat" },
    { value: "Assam - Kamrup", label: "Assam - Kamrup" },
    { value: "Assam - Karbi-Anglong", label: "Assam - Karbi-Anglong" },
    { value: "Assam - Karimganj", label: "Assam - Karimganj" },
    { value: "Assam - Kokrajhar", label: "Assam - Kokrajhar" },
    { value: "Assam - Lakhimpur", label: "Assam - Lakhimpur" },
    { value: "Assam - Morigaon", label: "Assam - Morigaon" },
    { value: "Assam - N.C.Hills", label: "Assam - N.C.Hills" },
    { value: "Assam - Nagaon", label: "Assam - Nagaon" },
    { value: "Assam - Nalbari", label: "Assam - Nalbari" },
    { value: "Assam - Sibsagar", label: "Assam - Sibsagar" },
    { value: "Assam - Sonitpur", label: "Assam - Sonitpur" },
    { value: "Assam - Tinsukia", label: "Assam - Tinsukia" },
    { value: "Bihar - Araria", label: "Bihar - Araria" },
    { value: "Bihar - Aurangabad", label: "Bihar - Aurangabad" },
    { value: "Bihar - Banka", label: "Bihar - Banka" },
    { value: "Bihar - Begusarai", label: "Bihar - Begusarai" },
    { value: "Bihar - Bhabua", label: "Bihar - Bhabua" },
    { value: "Bihar - Bhagalpur", label: "Bihar - Bhagalpur" },
    { value: "Bihar - Bhojpur(Arah)", label: "Bihar - Bhojpur(Arah)" },
    { value: "Bihar - Buxar", label: "Bihar - Buxar" },
    { value: "Bihar - Darbhanga", label: "Bihar - Darbhanga" },
    { value: "Bihar - East Champaran", label: "Bihar - East Champaran" },
    { value: "Bihar - Gaya", label: "Bihar - Gaya" },
    { value: "Bihar - Gopalganj", label: "Bihar - Gopalganj" },
    { value: "Bihar - Jamui", label: "Bihar - Jamui" },
    { value: "Bihar - Jehanabad", label: "Bihar - Jehanabad" },
    { value: "Bihar - Katihar", label: "Bihar - Katihar" },
    { value: "Bihar - Khagaria", label: "Bihar - Khagaria" },
    { value: "Bihar - Kishanganj", label: "Bihar - Kishanganj" },
    { value: "Bihar - Lakhisarai", label: "Bihar - Lakhisarai" },
    { value: "Bihar - Madhepura", label: "Bihar - Madhepura" },
    { value: "Bihar - Madhubani", label: "Bihar - Madhubani" },
    { value: "Bihar - Munger", label: "Bihar - Munger" },
    { value: "Bihar - Muzaffarpur", label: "Bihar - Muzaffarpur" },
    { value: "Bihar - Nalanda", label: "Bihar - Nalanda" },
    { value: "Bihar - Nawada", label: "Bihar - Nawada" },
    { value: "Bihar - Patna", label: "Bihar - Patna" },
    { value: "Bihar - Purnea", label: "Bihar - Purnea" },
    { value: "Bihar - Rohtas(Sasaram)", label: "Bihar - Rohtas(Sasaram)" },
    { value: "Bihar - Saharsa", label: "Bihar - Saharsa" },
    { value: "Bihar - Samastipur", label: "Bihar - Samastipur" },
    { value: "Bihar - Saran( Chapra )", label: "Bihar - Saran( Chapra )" },
    { value: "Bihar - Sekhpura", label: "Bihar - Sekhpura" },
    { value: "Bihar - Seohar", label: "Bihar - Seohar" },
    { value: "Bihar - Sitamarhi", label: "Bihar - Sitamarhi" },
    { value: "Bihar - Siwan", label: "Bihar - Siwan" },
    { value: "Bihar - Supaul", label: "Bihar - Supaul" },
    { value: "Bihar - Vaishali(Hajipur)", label: "Bihar - Vaishali(Hajipur)" },
    { value: "Bihar - West Champaran", label: "Bihar - West Champaran" },
    { value: "Chandigarh - Chandigarh", label: "Chandigarh - Chandigarh" },
    { value: "Chattisgarh - Bastar", label: "Chattisgarh - Bastar" },
    { value: "Chattisgarh - Bilaspur", label: "Chattisgarh - Bilaspur" },
    { value: "Chattisgarh - Dantewada", label: "Chattisgarh - Dantewada" },
    { value: "Chattisgarh - Dhamtari", label: "Chattisgarh - Dhamtari" },
    { value: "Chattisgarh - Durg", label: "Chattisgarh - Durg" },
    { value: "Chattisgarh - Janjgir-Champa", label: "Chattisgarh - Janjgir-Champa" },
    { value: "Chattisgarh - Jashpur", label: "Chattisgarh - Jashpur" },
    { value: "Chattisgarh - Kanker", label: "Chattisgarh - Kanker" },
    { value: "Chattisgarh - Kawardha", label: "Chattisgarh - Kawardha" },
    { value: "Chattisgarh - Korba", label: "Chattisgarh - Korba" },
    { value: "Chattisgarh - Koriya", label: "Chattisgarh - Koriya" },
    { value: "Chattisgarh - Mahasamund", label: "Chattisgarh - Mahasamund" },
    { value: "Chattisgarh - Raigarh", label: "Chattisgarh - Raigarh" },
    { value: "Chattisgarh - Raipur", label: "Chattisgarh - Raipur" },
    { value: "Chattisgarh - Rajnandgaon", label: "Chattisgarh - Rajnandgaon" },
    { value: "Chattisgarh - Surguja", label: "Chattisgarh - Surguja" },
    { value: "Dadra &amp; Nagar - Dadra", label: "Dadra &amp; Nagar - Dadra" },
    { value: "Daman &amp; Diu - Daman", label: "Daman &amp; Diu - Daman" },
    { value: "Daman &amp; Diu - Diu", label: "Daman &amp; Diu - Diu" },
    { value: "Delhi - Central", label: "Delhi - Central" },
    { value: "Delhi - New Delhi", label: "Delhi - New Delhi" },
    { value: "Delhi - North", label: "Delhi - North" },
    { value: "Delhi - North East", label: "Delhi - North East" },
    { value: "Delhi - North West", label: "Delhi - North West" },
    { value: "Delhi - South West", label: "Delhi - South West" },
    { value: "Delhi - West", label: "Delhi - West" },
    { value: "Goa - North Goa", label: "Goa - North Goa" },
    { value: "Goa - South Goa", label: "Goa - South Goa" },
    { value: "Gujarat - Ahmedabad", label: "Gujarat - Ahmedabad" },
    { value: "Gujarat - Amrela", label: "Gujarat - Amrela" },
    { value: "Gujarat - Anand", label: "Gujarat - Anand" },
    { value: "Gujarat - Banaskantha", label: "Gujarat - Banaskantha" },
    { value: "Gujarat - Bharuch", label: "Gujarat - Bharuch" },
    { value: "Gujarat - Bhavnagar", label: "Gujarat - Bhavnagar" },
    { value: "Gujarat - Dahod", label: "Gujarat - Dahod" },
    { value: "Gujarat - Dangs", label: "Gujarat - Dangs" },
    { value: "Gujarat - Gandhinagar", label: "Gujarat - Gandhinagar" },
    { value: "Gujarat - Jamnagar", label: "Gujarat - Jamnagar" },
    { value: "Gujarat - Junagadh", label: "Gujarat - Junagadh" },
    { value: "Gujarat - Kheda", label: "Gujarat - Kheda" },
    { value: "Gujarat - Kutch", label: "Gujarat - Kutch" },
    { value: "Gujarat - Mehsana", label: "Gujarat - Mehsana" },
    { value: "Gujarat - Narmada", label: "Gujarat - Narmada" },
    { value: "Gujarat - Navsari", label: "Gujarat - Navsari" },
    { value: "Gujarat - Panchmahals", label: "Gujarat - Panchmahals" },
    { value: "Gujarat - Patan", label: "Gujarat - Patan" },
    { value: "Gujarat - Porbander", label: "Gujarat - Porbander" },
    { value: "Gujarat - Rajkot", label: "Gujarat - Rajkot" },
    { value: "Gujarat - Sabarkantha", label: "Gujarat - Sabarkantha" },
    { value: "Gujarat - Surat", label: "Gujarat - Surat" },
    { value: "Gujarat - Surendranagar", label: "Gujarat - Surendranagar" },
    { value: "Gujarat - Vadodara", label: "Gujarat - Vadodara" },
    { value: "Gujarat - Valsad", label: "Gujarat - Valsad" },
    { value: "Haryana - Ambala", label: "Haryana - Ambala" },
    { value: "Haryana - Bhiwani", label: "Haryana - Bhiwani" },
    { value: "Haryana - Faridabad", label: "Haryana - Faridabad" },
    { value: "Haryana - Fatehabad", label: "Haryana - Fatehabad" },
    { value: "Haryana - Gurgaon", label: "Haryana - Gurgaon" },
    { value: "Haryana - Hissar", label: "Haryana - Hissar" },
    { value: "Haryana - Jhanjhar", label: "Haryana - Jhanjhar" },
    { value: "Haryana - Jind", label: "Haryana - Jind" },
    { value: "Haryana - Kaithal", label: "Haryana - Kaithal" },
    { value: "Haryana - Karnal", label: "Haryana - Karnal" },
    { value: "Haryana - Kurukshetra", label: "Haryana - Kurukshetra" },
    { value: "Haryana - Mahendragarh", label: "Haryana - Mahendragarh" },
    { value: "Haryana - Panchkula", label: "Haryana - Panchkula" },
    { value: "Haryana - Panipat", label: "Haryana - Panipat" },
    { value: "Haryana - Rewari", label: "Haryana - Rewari" },
    { value: "Haryana - Rohtak", label: "Haryana - Rohtak" },
    { value: "Haryana - Sirsa", label: "Haryana - Sirsa" },
    { value: "Haryana - Sonipat", label: "Haryana - Sonipat" },
    { value: "Haryana - Yamunanagar", label: "Haryana - Yamunanagar" },
    { value: "Himachal Pradesh - Bilaspur", label: "Himachal Pradesh - Bilaspur" },
    { value: "Himachal Pradesh - Chamba", label: "Himachal Pradesh - Chamba" },
    { value: "Himachal Pradesh - Hamirpur", label: "Himachal Pradesh - Hamirpur" },
    { value: "Himachal Pradesh - Kangra", label: "Himachal Pradesh - Kangra" },
    { value: "Himachal Pradesh - Kinnaur", label: "Himachal Pradesh - Kinnaur" },
    { value: "Himachal Pradesh - Kullu", label: "Himachal Pradesh - Kullu" },
    { value: "Himachal Pradesh - Lahaul-Spiti", label: "Himachal Pradesh - Lahaul-Spiti" },
    { value: "Himachal Pradesh - Mandi", label: "Himachal Pradesh - Mandi" },
    { value: "Himachal Pradesh - Shimla", label: "Himachal Pradesh - Shimla" },
    { value: "Himachal Pradesh - Sirmour", label: "Himachal Pradesh - Sirmour" },
    { value: "Himachal Pradesh - Solan", label: "Himachal Pradesh - Solan" },
    { value: "Himachal Pradesh - Una", label: "Himachal Pradesh - Una" },
    { value: "Jammu &amp; Kashmir - Anantnag", label: "Jammu &amp; Kashmir - Anantnag" },
    { value: "Jammu &amp; Kashmir - Badgan", label: "Jammu &amp; Kashmir - Badgan" },
    { value: "Jammu &amp; Kashmir - Baramula", label: "Jammu &amp; Kashmir - Baramula" },
    { value: "Jammu &amp; Kashmir - Doda", label: "Jammu &amp; Kashmir - Doda" },
    { value: "Jammu &amp; Kashmir - Jammu", label: "Jammu &amp; Kashmir - Jammu" },
    { value: "Jammu &amp; Kashmir - Kargil", label: "Jammu &amp; Kashmir - Kargil" },
    { value: "Jammu &amp; Kashmir - Kathua", label: "Jammu &amp; Kashmir - Kathua" },
    { value: "Jammu &amp; Kashmir - Kupwara", label: "Jammu &amp; Kashmir - Kupwara" },
    { value: "Jammu &amp; Kashmir - Leh", label: "Jammu &amp; Kashmir - Leh" },
    { value: "Jammu &amp; Kashmir - Poonch", label: "Jammu &amp; Kashmir - Poonch" },
    { value: "Jammu &amp; Kashmir - Pulwama", label: "Jammu &amp; Kashmir - Pulwama" },
    { value: "Jammu &amp; Kashmir - Rajauri", label: "Jammu &amp; Kashmir - Rajauri" },
    { value: "Jammu &amp; Kashmir - Srinagar", label: "Jammu &amp; Kashmir - Srinagar" },
    { value: "Jammu &amp; Kashmir - Udhampur", label: "Jammu &amp; Kashmir - Udhampur" },
    { value: "Jharkhand - Bokaro", label: "Jharkhand - Bokaro" },
    { value: "Jharkhand - Chaibasa(West Singhbhum)", label: "Jharkhand - Chaibasa(West Singhbhum)" },
    { value: "Jharkhand - Chatra", label: "Jharkhand - Chatra" },
    { value: "Jharkhand - Deoghar", label: "Jharkhand - Deoghar" },
    { value: "Jharkhand - Dhanbad", label: "Jharkhand - Dhanbad" },
    { value: "Jharkhand - Dumka", label: "Jharkhand - Dumka" },
    { value: "Jharkhand - Garhwa", label: "Jharkhand - Garhwa" },
    { value: "Jharkhand - Giridih", label: "Jharkhand - Giridih" },
    { value: "Jharkhand - Godda", label: "Jharkhand - Godda" },
    { value: "Jharkhand - Gumla", label: "Jharkhand - Gumla" },
    { value: "Jharkhand - Hazaribagh", label: "Jharkhand - Hazaribagh" },
    { value: "Jharkhand - Jamshedpur(East Singhbhum)", label: "Jharkhand - Jamshedpur(East Singhbhum)" },
    { value: "Jharkhand - Jamtara", label: "Jharkhand - Jamtara" },
    { value: "Jharkhand - Koderma", label: "Jharkhand - Koderma" },
    { value: "Jharkhand - Latehar", label: "Jharkhand - Latehar" },
    { value: "Jharkhand - Lohardaga", label: "Jharkhand - Lohardaga" },
    { value: "Jharkhand - Pakur", label: "Jharkhand - Pakur" },
    { value: "Jharkhand - Palamu", label: "Jharkhand - Palamu" },
    { value: "Jharkhand - Ranchi", label: "Jharkhand - Ranchi" },
    { value: "Jharkhand - Sahebganj", label: "Jharkhand - Sahebganj" },
    { value: "Jharkhand - Saraikela", label: "Jharkhand - Saraikela" },
    { value: "Jharkhand - Simdega", label: "Jharkhand - Simdega" },
    { value: "Karnataka - Bangalore Rural", label: "Karnataka - Bangalore Rural" },
    { value: "Karnataka - Bangalore Urban", label: "Karnataka - Bangalore Urban" },
    { value: "Karnataka - Belgaum", label: "Karnataka - Belgaum" },
    { value: "Karnataka - Bellary", label: "Karnataka - Bellary" },
    { value: "Karnataka - Bidar", label: "Karnataka - Bidar" },
    { value: "Karnataka - Bijapur", label: "Karnataka - Bijapur" },
    { value: "Karnataka - Chamrajnagar", label: "Karnataka - Chamrajnagar" },
    { value: "Karnataka - Chickmagalur", label: "Karnataka - Chickmagalur" },
    { value: "Karnataka - Chitradurga", label: "Karnataka - Chitradurga" },
    { value: "Karnataka - Dakshina Kannada", label: "Karnataka - Dakshina Kannada" },
    { value: "Karnataka - Davanagare", label: "Karnataka - Davanagare" },
    { value: "Karnataka - Dharwad", label: "Karnataka - Dharwad" },
    { value: "Karnataka - Gadak", label: "Karnataka - Gadak" },
    { value: "Karnataka - Gulberga", label: "Karnataka - Gulberga" },
    { value: "Karnataka - Hassan", label: "Karnataka - Hassan" },
    { value: "Karnataka - Haveri", label: "Karnataka - Haveri" },
    { value: "Karnataka - Karwar", label: "Karnataka - Karwar" },
    { value: "Karnataka - Kolar", label: "Karnataka - Kolar" },
    { value: "Karnataka - Koppal", label: "Karnataka - Koppal" },
    { value: "Karnataka - Madikeri", label: "Karnataka - Madikeri" },
    { value: "Karnataka - Mandya", label: "Karnataka - Mandya" },
    { value: "Karnataka - Mysore", label: "Karnataka - Mysore" },
    { value: "Karnataka - Raichur", label: "Karnataka - Raichur" },
    { value: "Karnataka - Shimoga", label: "Karnataka - Shimoga" },
    { value: "Karnataka - Tumkur", label: "Karnataka - Tumkur" },
    { value: "Karnataka - Udupi", label: "Karnataka - Udupi" },
    { value: "Karnataka - Yadgir", label: "Karnataka - Yadgir" },
    { value: "Kerala - Alapuzzha", label: "Kerala - Alapuzzha" },
    { value: "Kerala - Cannanore", label: "Kerala - Cannanore" },
    { value: "Kerala - Ernakulam", label: "Kerala - Ernakulam" },
    { value: "Kerala - Idukki", label: "Kerala - Idukki" },
    { value: "Kerala - Kasaragod", label: "Kerala - Kasaragod" },
    { value: "Kerala - Kottayam", label: "Kerala - Kottayam" },
    { value: "Kerala - Kozhikode", label: "Kerala - Kozhikode" },
    { value: "Kerala - Mallapuram", label: "Kerala - Mallapuram" },
    { value: "Kerala - Palghat", label: "Kerala - Palghat" },
    { value: "Kerala - Pathanamthitta", label: "Kerala - Pathanamthitta" },
    { value: "Kerala - Quilon", label: "Kerala - Quilon" },
    { value: "Kerala - Trichur", label: "Kerala - Trichur" },
    { value: "Kerala - Trivandrum", label: "Kerala - Trivandrum" },
    { value: "Kerala - Wayanad", label: "Kerala - Wayanad" },
    { value: "Lakshdweep - Lakshdweep", label: "Lakshdweep - Lakshdweep" },
    { value: "Madhya Pradesh - Anooppur", label: "Madhya Pradesh - Anooppur" },
    { value: "Madhya Pradesh - Ashoknagar", label: "Madhya Pradesh - Ashoknagar" },
    { value: "Madhya Pradesh - Badwani", label: "Madhya Pradesh - Badwani" },
    { value: "Madhya Pradesh - Balaghat", label: "Madhya Pradesh - Balaghat" },
    { value: "Madhya Pradesh - Betul", label: "Madhya Pradesh - Betul" },
    { value: "Madhya Pradesh - Bhind", label: "Madhya Pradesh - Bhind" },
    { value: "Madhya Pradesh - Bhopal", label: "Madhya Pradesh - Bhopal" },
    { value: "Madhya Pradesh - Burhanpur", label: "Madhya Pradesh - Burhanpur" },
    { value: "Madhya Pradesh - Chhattarpur", label: "Madhya Pradesh - Chhattarpur" },
    { value: "Madhya Pradesh - Chhindwara", label: "Madhya Pradesh - Chhindwara" },
    { value: "Madhya Pradesh - Damoh", label: "Madhya Pradesh - Damoh" },
    { value: "Madhya Pradesh - Datia", label: "Madhya Pradesh - Datia" },
    { value: "Madhya Pradesh - Dewas", label: "Madhya Pradesh - Dewas" },
    { value: "Madhya Pradesh - Dhar", label: "Madhya Pradesh - Dhar" },
    { value: "Madhya Pradesh - Dindori", label: "Madhya Pradesh - Dindori" },
    { value: "Madhya Pradesh - Guna", label: "Madhya Pradesh - Guna" },
    { value: "Madhya Pradesh - Gwalior", label: "Madhya Pradesh - Gwalior" },
    { value: "Madhya Pradesh - Harda", label: "Madhya Pradesh - Harda" },
    { value: "Madhya Pradesh - Hoshangabad", label: "Madhya Pradesh - Hoshangabad" },
    { value: "Madhya Pradesh - Indore", label: "Madhya Pradesh - Indore" },
    { value: "Madhya Pradesh - Jabalpur", label: "Madhya Pradesh - Jabalpur" },
    { value: "Madhya Pradesh - Jhabua", label: "Madhya Pradesh - Jhabua" },
    { value: "Madhya Pradesh - Katni", label: "Madhya Pradesh - Katni" },
    { value: "Madhya Pradesh - Khandwa", label: "Madhya Pradesh - Khandwa" },
    { value: "Madhya Pradesh - Khargone", label: "Madhya Pradesh - Khargone" },
    { value: "Madhya Pradesh - Mandla", label: "Madhya Pradesh - Mandla" },
    { value: "Madhya Pradesh - Mandsaur", label: "Madhya Pradesh - Mandsaur" },
    { value: "Madhya Pradesh - Morena", label: "Madhya Pradesh - Morena" },
    { value: "Madhya Pradesh - Narsinghpur", label: "Madhya Pradesh - Narsinghpur" },
    { value: "Madhya Pradesh - Neemuch", label: "Madhya Pradesh - Neemuch" },
    { value: "Madhya Pradesh - Panna", label: "Madhya Pradesh - Panna" },
    { value: "Madhya Pradesh - Raisen", label: "Madhya Pradesh - Raisen" },
    { value: "Madhya Pradesh - Rajgarh", label: "Madhya Pradesh - Rajgarh" },
    { value: "Madhya Pradesh - Ratlam", label: "Madhya Pradesh - Ratlam" },
    { value: "Madhya Pradesh - Rewa", label: "Madhya Pradesh - Rewa" },
    { value: "Madhya Pradesh - Sagar", label: "Madhya Pradesh - Sagar" },
    { value: "Madhya Pradesh - Satna", label: "Madhya Pradesh - Satna" },
    { value: "Madhya Pradesh - Sehore", label: "Madhya Pradesh - Sehore" },
    { value: "Madhya Pradesh - Seoni", label: "Madhya Pradesh - Seoni" },
    { value: "Madhya Pradesh - Shahdol", label: "Madhya Pradesh - Shahdol" },
    { value: "Madhya Pradesh - Shajapur", label: "Madhya Pradesh - Shajapur" },
    { value: "Madhya Pradesh - Sheopur", label: "Madhya Pradesh - Sheopur" },
    { value: "Madhya Pradesh - Shivpuri", label: "Madhya Pradesh - Shivpuri" },
    { value: "Madhya Pradesh - Sindi", label: "Madhya Pradesh - Sindi" },
    { value: "Madhya Pradesh - Tikamgarh", label: "Madhya Pradesh - Tikamgarh" },
    { value: "Madhya Pradesh - Ujjain", label: "Madhya Pradesh - Ujjain" },
    { value: "Madhya Pradesh - Umaria", label: "Madhya Pradesh - Umaria" },
    { value: "Madhya Pradesh - Vidisha", label: "Madhya Pradesh - Vidisha" },
    { value: "Maharashtra - Ahmednagar", label: "Maharashtra - Ahmednagar" },
    { value: "Maharashtra - Akola", label: "Maharashtra - Akola" },
    { value: "Maharashtra - Amravati", label: "Maharashtra - Amravati" },
    { value: "Maharashtra - Aurangabad", label: "Maharashtra - Aurangabad" },
    { value: "Maharashtra - Bandra(Mumbai Suburban district)", label: "Maharashtra - Bandra(Mumbai Suburban district)" },
    { value: "Maharashtra - Beed", label: "Maharashtra - Beed" },
    { value: "Maharashtra - Bhandara", label: "Maharashtra - Bhandara" },
    { value: "Maharashtra - Buldhana", label: "Maharashtra - Buldhana" },
    { value: "Maharashtra - Chandrapur", label: "Maharashtra - Chandrapur" },
    { value: "Maharashtra - Dhule", label: "Maharashtra - Dhule" },
    { value: "Maharashtra - Gadchiroli", label: "Maharashtra - Gadchiroli" },
    { value: "Maharashtra - Gondia", label: "Maharashtra - Gondia" },
    { value: "Maharashtra - Hingoli", label: "Maharashtra - Hingoli" },
    { value: "Maharashtra - Jalgaon", label: "Maharashtra - Jalgaon" },
    { value: "Maharashtra - Jalna", label: "Maharashtra - Jalna" },
    { value: "Maharashtra - Kolhpur", label: "Maharashtra - Kolhpur" },
    { value: "Maharashtra - Latur", label: "Maharashtra - Latur" },
    { value: "Maharashtra - Mumbai-City", label: "Maharashtra - Mumbai-City" },
    { value: "Maharashtra - Nagpur", label: "Maharashtra - Nagpur" },
    { value: "Maharashtra - Nanded", label: "Maharashtra - Nanded" },
    { value: "Maharashtra - Nandurbar", label: "Maharashtra - Nandurbar" },
    { value: "Maharashtra - Nashik", label: "Maharashtra - Nashik" },
    { value: "Maharashtra - Osmanabad", label: "Maharashtra - Osmanabad" },
    { value: "Maharashtra - Parbhani", label: "Maharashtra - Parbhani" },
    { value: "Maharashtra - Pune", label: "Maharashtra - Pune" },
    { value: "Maharashtra - Raigad", label: "Maharashtra - Raigad" },
    { value: "Maharashtra - Ratnagiri", label: "Maharashtra - Ratnagiri" },
    { value: "Maharashtra - Sangli", label: "Maharashtra - Sangli" },
    { value: "Maharashtra - Satara", label: "Maharashtra - Satara" },
    { value: "Maharashtra - Sholapur", label: "Maharashtra - Sholapur" },
    { value: "Maharashtra - Sindudurg", label: "Maharashtra - Sindudurg" },
    { value: "Maharashtra - Thane", label: "Maharashtra - Thane" },
    { value: "Maharashtra - Wardha", label: "Maharashtra - Wardha" },
    { value: "Maharashtra - Washim", label: "Maharashtra - Washim" },
    { value: "Maharashtra - Yavatmal", label: "Maharashtra - Yavatmal" },
    { value: "Manipur - Bishnupur", label: "Manipur - Bishnupur" },
    { value: "Manipur - Chandel", label: "Manipur - Chandel" },
    { value: "Manipur - Churachandpur", label: "Manipur - Churachandpur" },
    { value: "Manipur - Imphal East", label: "Manipur - Imphal East" },
    { value: "Manipur - Imphal West", label: "Manipur - Imphal West" },
    { value: "Manipur - Senapati", label: "Manipur - Senapati" },
    { value: "Manipur - Tamenglong", label: "Manipur - Tamenglong" },
    { value: "Manipur - Thoubal", label: "Manipur - Thoubal" },
    { value: "Manipur - Ukhrul", label: "Manipur - Ukhrul" },
    { value: "Meghalaya - East Garo Hill", label: "Meghalaya - East Garo Hill" },
    { value: "Meghalaya - East Khasi Hill", label: "Meghalaya - East Khasi Hill" },
    { value: "Meghalaya - Jaintia Hill", label: "Meghalaya - Jaintia Hill" },
    { value: "Meghalaya - Ri-Bhoi District", label: "Meghalaya - Ri-Bhoi District" },
    { value: "Meghalaya - South Garo Hills", label: "Meghalaya - South Garo Hills" },
    { value: "Meghalaya - West Garo Hill", label: "Meghalaya - West Garo Hill" },
    { value: "Meghalaya - West Khasi Hill", label: "Meghalaya - West Khasi Hill" },
    { value: "Mizoram - Aizawal", label: "Mizoram - Aizawal" },
    { value: "Mizoram - Champhai", label: "Mizoram - Champhai" },
    { value: "Mizoram - Chimtipui District", label: "Mizoram - Chimtipui District" },
    { value: "Mizoram - Kolasib", label: "Mizoram - Kolasib" },
    { value: "Mizoram - Lawngtlai", label: "Mizoram - Lawngtlai" },
    { value: "Mizoram - Luglei District", label: "Mizoram - Luglei District" },
    { value: "Mizoram - Mamit", label: "Mizoram - Mamit" },
    { value: "Mizoram - Serchhip", label: "Mizoram - Serchhip" },
    { value: "Nagaland - Dimapur", label: "Nagaland - Dimapur" },
    { value: "Nagaland - Kohima", label: "Nagaland - Kohima" },
    { value: "Nagaland - Mokokchung", label: "Nagaland - Mokokchung" },
    { value: "Nagaland - Mon", label: "Nagaland - Mon" },
    { value: "Nagaland - Phek", label: "Nagaland - Phek" },
    { value: "Nagaland - Tuensang", label: "Nagaland - Tuensang" },
    { value: "Nagaland - Wokha", label: "Nagaland - Wokha" },
    { value: "Nagaland - Zunheboto", label: "Nagaland - Zunheboto" },
    { value: "Orissa - Angul", label: "Orissa - Angul" },
    { value: "Orissa - Balangir", label: "Orissa - Balangir" },
    { value: "Orissa - Balasore", label: "Orissa - Balasore" },
    { value: "Orissa - Bargah", label: "Orissa - Bargah" },
    { value: "Orissa - Bhadrak", label: "Orissa - Bhadrak" },
    { value: "Orissa - Boudh", label: "Orissa - Boudh" },
    { value: "Orissa - Cuttak", label: "Orissa - Cuttak" },
    { value: "Orissa - Deogarh", label: "Orissa - Deogarh" },
    { value: "Orissa - Dhenkanal", label: "Orissa - Dhenkanal" },
    { value: "Orissa - Gajapati", label: "Orissa - Gajapati" },
    { value: "Orissa - Ganjam", label: "Orissa - Ganjam" },
    { value: "Orissa - Jagatsinghpur", label: "Orissa - Jagatsinghpur" },
    { value: "Orissa - Jajpur", label: "Orissa - Jajpur" },
    { value: "Orissa - Jharsuguda", label: "Orissa - Jharsuguda" },
    { value: "Orissa - Kalhandi", label: "Orissa - Kalhandi" },
    { value: "Orissa - Kendrapara", label: "Orissa - Kendrapara" },
    { value: "Orissa - Keonjhar", label: "Orissa - Keonjhar" },
    { value: "Orissa - Khurda", label: "Orissa - Khurda" },
    { value: "Orissa - Koraput", label: "Orissa - Koraput" },
    { value: "Orissa - Malkangiri", label: "Orissa - Malkangiri" },
    { value: "Orissa - Mayurbhanj", label: "Orissa - Mayurbhanj" },
    { value: "Orissa - Navapada", label: "Orissa - Navapada" },
    { value: "Orissa - Navaragpur", label: "Orissa - Navaragpur" },
    { value: "Orissa - Nayagarh", label: "Orissa - Nayagarh" },
    { value: "Orissa - Phulbani", label: "Orissa - Phulbani" },
    { value: "Orissa - Puri", label: "Orissa - Puri" },
    { value: "Orissa - Rayagada", label: "Orissa - Rayagada" },
    { value: "Orissa - Sambalpur", label: "Orissa - Sambalpur" },
    { value: "Orissa - Sonepur", label: "Orissa - Sonepur" },
    { value: "Orissa - Sundergarh", label: "Orissa - Sundergarh" },
    { value: "Pondicherry - Karikal", label: "Pondicherry - Karikal" },
    { value: "Pondicherry - Mahe", label: "Pondicherry - Mahe" },
    { value: "Pondicherry - Pondicherry", label: "Pondicherry - Pondicherry" },
    { value: "Pondicherry - Yaman", label: "Pondicherry - Yaman" },
    { value: "Punjab - Amritsar", label: "Punjab - Amritsar" },
    { value: "Punjab - Bhatinda", label: "Punjab - Bhatinda" },
    { value: "Punjab - Faridkot", label: "Punjab - Faridkot" },
    { value: "Punjab - Fatehgarh Saheb", label: "Punjab - Fatehgarh Saheb" },
    { value: "Punjab - Ferozepur", label: "Punjab - Ferozepur" },
    { value: "Punjab - Gurdaspur", label: "Punjab - Gurdaspur" },
    { value: "Punjab - Hosiarpur", label: "Punjab - Hosiarpur" },
    { value: "Punjab - Jalandhar", label: "Punjab - Jalandhar" },
    { value: "Punjab - Kapurthala", label: "Punjab - Kapurthala" },
    { value: "Punjab - Ludhiana", label: "Punjab - Ludhiana" },
    { value: "Punjab - Mansa", label: "Punjab - Mansa" },
    { value: "Punjab - Moga", label: "Punjab - Moga" },
    { value: "Punjab - Muktsar", label: "Punjab - Muktsar" },
    { value: "Punjab - Navansahar", label: "Punjab - Navansahar" },
    { value: "Punjab - Patiala", label: "Punjab - Patiala" },
    { value: "Punjab - Ropar", label: "Punjab - Ropar" },
    { value: "Punjab - Sangrur", label: "Punjab - Sangrur" },
    { value: "Rajasthan - Ajmer", label: "Rajasthan - Ajmer" },
    { value: "Rajasthan - Alwar", label: "Rajasthan - Alwar" },
    { value: "Rajasthan - Banswara", label: "Rajasthan - Banswara" },
    { value: "Rajasthan - Baran", label: "Rajasthan - Baran" },
    { value: "Rajasthan - Barmer", label: "Rajasthan - Barmer" },
    { value: "Rajasthan - Bharatpur", label: "Rajasthan - Bharatpur" },
    { value: "Rajasthan - Bhilwara", label: "Rajasthan - Bhilwara" },
    { value: "Rajasthan - Bikaner", label: "Rajasthan - Bikaner" },
    { value: "Rajasthan - Bundi", label: "Rajasthan - Bundi" },
    { value: "Rajasthan - Chittorgarh", label: "Rajasthan - Chittorgarh" },
    { value: "Rajasthan - Churu", label: "Rajasthan - Churu" },
    { value: "Rajasthan - Dausa", label: "Rajasthan - Dausa" },
    { value: "Rajasthan - Dholpur", label: "Rajasthan - Dholpur" },
    { value: "Rajasthan - Dungarpur", label: "Rajasthan - Dungarpur" },
    { value: "Rajasthan - Ganganagar", label: "Rajasthan - Ganganagar" },
    { value: "Rajasthan - Hanumangarh", label: "Rajasthan - Hanumangarh" },
    { value: "Rajasthan - Jaipur", label: "Rajasthan - Jaipur" },
    { value: "Rajasthan - Jaisalmer", label: "Rajasthan - Jaisalmer" },
    { value: "Rajasthan - Jalor", label: "Rajasthan - Jalor" },
    { value: "Rajasthan - Jhalawar", label: "Rajasthan - Jhalawar" },
    { value: "Rajasthan - Jhunjhunu", label: "Rajasthan - Jhunjhunu" },
    { value: "Rajasthan - Jodhpur", label: "Rajasthan - Jodhpur" },
    { value: "Rajasthan - Karauli", label: "Rajasthan - Karauli" },
    { value: "Rajasthan - Kota", label: "Rajasthan - Kota" },
    { value: "Rajasthan - Nagaur", label: "Rajasthan - Nagaur" },
    { value: "Rajasthan - Pali", label: "Rajasthan - Pali" },
    { value: "Rajasthan - Rajsamand", label: "Rajasthan - Rajsamand" },
    { value: "Rajasthan - Sawai Madhopur", label: "Rajasthan - Sawai Madhopur" },
    { value: "Rajasthan - Sikar", label: "Rajasthan - Sikar" },
    { value: "Rajasthan - Sirohi", label: "Rajasthan - Sirohi" },
    { value: "Rajasthan - Tonk", label: "Rajasthan - Tonk" },
    { value: "Rajasthan - Udaipur", label: "Rajasthan - Udaipur" },
    { value: "Sikkim - East", label: "Sikkim - East" },
    { value: "Sikkim - North", label: "Sikkim - North" },
    { value: "Sikkim - South", label: "Sikkim - South" },
    { value: "Sikkim - West", label: "Sikkim - West" },
    { value: "Tamil Nadu - Chennai", label: "Tamil Nadu - Chennai" },
    { value: "Tamil Nadu - Coimbotore", label: "Tamil Nadu - Coimbotore" },
    { value: "Tamil Nadu - Cuddalorei", label: "Tamil Nadu - Cuddalorei" },
    { value: "Tamil Nadu - Dharmapuri", label: "Tamil Nadu - Dharmapuri" },
    { value: "Tamil Nadu - Dindigul", label: "Tamil Nadu - Dindigul" },
    { value: "Tamil Nadu - Erode", label: "Tamil Nadu - Erode" },
    { value: "Tamil Nadu - Kancheepuram", label: "Tamil Nadu - Kancheepuram" },
    { value: "Tamil Nadu - Kanniyakumari (HQ : Nagercoil)", label: "Tamil Nadu - Kanniyakumari (HQ : Nagercoil)" },
    { value: "Tamil Nadu - Karur", label: "Tamil Nadu - Karur" },
    { value: "Tamil Nadu - Madurai", label: "Tamil Nadu - Madurai" },
    { value: "Tamil Nadu - Nagapattinam", label: "Tamil Nadu - Nagapattinam" },
    { value: "Tamil Nadu - Namakkal", label: "Tamil Nadu - Namakkal" },
    { value: "Tamil Nadu - Nilgiris (HQ: Udhagamandalam)", label: "Tamil Nadu - Nilgiris (HQ: Udhagamandalam)" },
    { value: "Tamil Nadu - Perambalur", label: "Tamil Nadu - Perambalur" },
    { value: "Tamil Nadu - Pudukkottai", label: "Tamil Nadu - Pudukkottai" },
    { value: "Tamil Nadu - Ramanathapuram", label: "Tamil Nadu - Ramanathapuram" },
    { value: "Tamil Nadu - Salem", label: "Tamil Nadu - Salem" },
    { value: "Tamil Nadu - Sivaganga", label: "Tamil Nadu - Sivaganga" },
    { value: "Tamil Nadu - Thanjavur", label: "Tamil Nadu - Thanjavur" },
    { value: "Tamil Nadu - Theni", label: "Tamil Nadu - Theni" },
    { value: "Tamil Nadu - Thoothkudi", label: "Tamil Nadu - Thoothkudi" },
    { value: "Tamil Nadu - Tiruchiorappalli", label: "Tamil Nadu - Tiruchiorappalli" },
    { value: "Tamil Nadu - Tirunelveli", label: "Tamil Nadu - Tirunelveli" },
    { value: "Tamil Nadu - Tiruvallur", label: "Tamil Nadu - Tiruvallur" },
    { value: "Tamil Nadu - Tiruvannamalai", label: "Tamil Nadu - Tiruvannamalai" },
    { value: "Tamil Nadu - Tiruvarur", label: "Tamil Nadu - Tiruvarur" },
    { value: "Tamil Nadu - Vellore", label: "Tamil Nadu - Vellore" },
    { value: "Tamil Nadu - Villupuram", label: "Tamil Nadu - Villupuram" },
    { value: "Tamil Nadu - Virudhunagar", label: "Tamil Nadu - Virudhunagar" },
    { value: "Tripura - Dhalai District", label: "Tripura - Dhalai District" },
    { value: "Tripura - North District", label: "Tripura - North District" },
    { value: "Tripura - South District", label: "Tripura - South District" },
    { value: "Tripura - West District", label: "Tripura - West District" },
    { value: "Uttar Pradesh - Agra", label: "Uttar Pradesh - Agra" },
    { value: "Uttar Pradesh - Aligarh", label: "Uttar Pradesh - Aligarh" },
    { value: "Uttar Pradesh - Allahabad", label: "Uttar Pradesh - Allahabad" },
    { value: "Uttar Pradesh - Ambedkarnagar", label: "Uttar Pradesh - Ambedkarnagar" },
    { value: "Uttar Pradesh - Azamgarh", label: "Uttar Pradesh - Azamgarh" },
    { value: "Uttar Pradesh - Bagpat", label: "Uttar Pradesh - Bagpat" },
    { value: "Uttar Pradesh - Bahraich", label: "Uttar Pradesh - Bahraich" },
    { value: "Uttar Pradesh - Balia", label: "Uttar Pradesh - Balia" },
    { value: "Uttar Pradesh - Balrampur", label: "Uttar Pradesh - Balrampur" },
    { value: "Uttar Pradesh - Banda", label: "Uttar Pradesh - Banda" },
    { value: "Uttar Pradesh - Barabanki", label: "Uttar Pradesh - Barabanki" },
    { value: "Uttar Pradesh - Bareilly", label: "Uttar Pradesh - Bareilly" },
    { value: "Uttar Pradesh - Basti", label: "Uttar Pradesh - Basti" },
    { value: "Uttar Pradesh - Bhadoi", label: "Uttar Pradesh - Bhadoi" },
    { value: "Uttar Pradesh - Bijnor", label: "Uttar Pradesh - Bijnor" },
    { value: "Uttar Pradesh - Budaun", label: "Uttar Pradesh - Budaun" },
    { value: "Uttar Pradesh - Bulandshehar", label: "Uttar Pradesh - Bulandshehar" },
    { value: "Uttar Pradesh - Chandauli", label: "Uttar Pradesh - Chandauli" },
    { value: "Uttar Pradesh - Deoria", label: "Uttar Pradesh - Deoria" },
    { value: "Uttar Pradesh - Etah", label: "Uttar Pradesh - Etah" },
    { value: "Uttar Pradesh - Etawah", label: "Uttar Pradesh - Etawah" },
    { value: "Uttar Pradesh - Faizabad", label: "Uttar Pradesh - Faizabad" },
    { value: "Uttar Pradesh - Farrukhabad", label: "Uttar Pradesh - Farrukhabad" },
    { value: "Uttar Pradesh - Fatehpur", label: "Uttar Pradesh - Fatehpur" },
    { value: "Uttar Pradesh - Firozabad", label: "Uttar Pradesh - Firozabad" },
    { value: "Uttar Pradesh - Gautam Bodda Nagar", label: "Uttar Pradesh - Gautam Bodda Nagar" },
    { value: "Uttar Pradesh - Gazipur", label: "Uttar Pradesh - Gazipur" },
    { value: "Uttar Pradesh - Ghaziabad", label: "Uttar Pradesh - Ghaziabad" },
    { value: "Uttar Pradesh - Gonda", label: "Uttar Pradesh - Gonda" },
    { value: "Uttar Pradesh - Gorakpur", label: "Uttar Pradesh - Gorakpur" },
    { value: "Uttar Pradesh - Hamirpur", label: "Uttar Pradesh - Hamirpur" },
    { value: "Uttar Pradesh - Hardoi", label: "Uttar Pradesh - Hardoi" },
    { value: "Uttar Pradesh - Jalaun", label: "Uttar Pradesh - Jalaun" },
    { value: "Uttar Pradesh - Jaunpur", label: "Uttar Pradesh - Jaunpur" },
    { value: "Uttar Pradesh - Jhansi", label: "Uttar Pradesh - Jhansi" },
    { value: "Uttar Pradesh - jyotiba Phoole Nagar", label: "Uttar Pradesh - jyotiba Phoole Nagar" },
    { value: "Uttar Pradesh - Kanooj", label: "Uttar Pradesh - Kanooj" },
    { value: "Uttar Pradesh - Kanpur Dehat", label: "Uttar Pradesh - Kanpur Dehat" },
    { value: "Uttar Pradesh - Kanpur(Nagar)", label: "Uttar Pradesh - Kanpur(Nagar)" },
    { value: "Uttar Pradesh - Kaushambi", label: "Uttar Pradesh - Kaushambi" },
    { value: "Uttar Pradesh - Lakhimpur-Khedi", label: "Uttar Pradesh - Lakhimpur-Khedi" },
    { value: "Uttar Pradesh - Lalitpur", label: "Uttar Pradesh - Lalitpur" },
    { value: "Uttar Pradesh - Lucknow", label: "Uttar Pradesh - Lucknow" },
    { value: "Uttar Pradesh - Maha Maya Nagar", label: "Uttar Pradesh - Maha Maya Nagar" },
    { value: "Uttar Pradesh - Maharajganj", label: "Uttar Pradesh - Maharajganj" },
    { value: "Uttar Pradesh - Mahoba", label: "Uttar Pradesh - Mahoba" },
    { value: "Uttar Pradesh - Mainpuri", label: "Uttar Pradesh - Mainpuri" },
    { value: "Uttar Pradesh - Mathura", label: "Uttar Pradesh - Mathura" },
    { value: "Uttar Pradesh - Mau", label: "Uttar Pradesh - Mau" },
    { value: "Uttar Pradesh - Meerut", label: "Uttar Pradesh - Meerut" },
    { value: "Uttar Pradesh - Mirzapur", label: "Uttar Pradesh - Mirzapur" },
    { value: "Uttar Pradesh - Moradabad", label: "Uttar Pradesh - Moradabad" },
    { value: "Uttar Pradesh - Muzaffar Nagar", label: "Uttar Pradesh - Muzaffar Nagar" },
    { value: "Uttar Pradesh - Oraiyya", label: "Uttar Pradesh - Oraiyya" },
    { value: "Uttar Pradesh - Padrauna", label: "Uttar Pradesh - Padrauna" },
    { value: "Uttar Pradesh - Pilibhit", label: "Uttar Pradesh - Pilibhit" },
    { value: "Uttar Pradesh - Pratapgarh", label: "Uttar Pradesh - Pratapgarh" },
    { value: "Uttar Pradesh - Raebareili", label: "Uttar Pradesh - Raebareili" },
    { value: "Uttar Pradesh - Rampur", label: "Uttar Pradesh - Rampur" },
    { value: "Uttar Pradesh - Saharanpur", label: "Uttar Pradesh - Saharanpur" },
    { value: "Uttar Pradesh - Sant Kabir Nagar", label: "Uttar Pradesh - Sant Kabir Nagar" },
    { value: "Uttar Pradesh - Shahjahanpur", label: "Uttar Pradesh - Shahjahanpur" },
    { value: "Uttar Pradesh - Shooji Maharaj", label: "Uttar Pradesh - Shooji Maharaj" },
    { value: "Uttar Pradesh - Shravati", label: "Uttar Pradesh - Shravati" },
    { value: "Uttar Pradesh - Siddharth Nagar", label: "Uttar Pradesh - Siddharth Nagar" },
    { value: "Uttar Pradesh - Sitapur", label: "Uttar Pradesh - Sitapur" },
    { value: "Uttar Pradesh - Sultanpur", label: "Uttar Pradesh - Sultanpur" },
    { value: "Uttar Pradesh - Sunbhadra", label: "Uttar Pradesh - Sunbhadra" },
    { value: "Uttar Pradesh - Unnav", label: "Uttar Pradesh - Unnav" },
    { value: "Uttar Pradesh - Varanasi", label: "Uttar Pradesh - Varanasi" },
    { value: "Uttaranchal - Almora", label: "Uttaranchal - Almora" },
    { value: "Uttaranchal - Bageshwar", label: "Uttaranchal - Bageshwar" },
    { value: "Uttaranchal - Chamoli( Gopeshwar )", label: "Uttaranchal - Chamoli( Gopeshwar )" },
    { value: "Uttaranchal - Champawat", label: "Uttaranchal - Champawat" },
    { value: "Uttaranchal - Dehradun", label: "Uttaranchal - Dehradun" },
    { value: "Uttaranchal - Garhwal(Pauri)", label: "Uttaranchal - Garhwal(Pauri)" },
    { value: "Uttaranchal - Haridwar", label: "Uttaranchal - Haridwar" },
    { value: "Uttaranchal - Nainital", label: "Uttaranchal - Nainital" },
    { value: "Uttaranchal - Pitoragarh", label: "Uttaranchal - Pitoragarh" },
    { value: "Uttaranchal - Rudraprayag", label: "Uttaranchal - Rudraprayag" },
    { value: "Uttaranchal - Tehri-Garhwal", label: "Uttaranchal - Tehri-Garhwal" },
    { value: "Uttaranchal - Udhamsingh Nagar", label: "Uttaranchal - Udhamsingh Nagar" },
    { value: "Uttaranchal - Uttarkashi", label: "Uttaranchal - Uttarkashi" },
    { value: "West Bengal - Bankura", label: "West Bengal - Bankura" },
    { value: "West Bengal - Bardhaman", label: "West Bengal - Bardhaman" },
    { value: "West Bengal - Birbhum", label: "West Bengal - Birbhum" },
    { value: "West Bengal - Coochbehar", label: "West Bengal - Coochbehar" },
    { value: "West Bengal - Dakshin Dinajpur", label: "West Bengal - Dakshin Dinajpur" },
    { value: "West Bengal - Darjeeling", label: "West Bengal - Darjeeling" },
    { value: "West Bengal - Hooghly", label: "West Bengal - Hooghly" },
    { value: "West Bengal - Howrah", label: "West Bengal - Howrah" },
    { value: "West Bengal - Jalpaiguri", label: "West Bengal - Jalpaiguri" },
    { value: "West Bengal - Malda", label: "West Bengal - Malda" },
    { value: "West Bengal - Medinipur", label: "West Bengal - Medinipur" },
    { value: "West Bengal - Murshidabad", label: "West Bengal - Murshidabad" },
    { value: "West Bengal - Nadia", label: "West Bengal - Nadia" },
    { value: "West Bengal - North 24 Parganas", label: "West Bengal - North 24 Parganas" },
    { value: "West Bengal - Purulia", label: "West Bengal - Purulia" },
    { value: "West Bengal - Siliguri", label: "West Bengal - Siliguri" },
    { value: "West Bengal - South 24 Parganas", label: "West Bengal - South 24 Parganas" },
    { value: "West Bengal - Uttar Dinajpur", label: "West Bengal - Uttar Dinajpur" },
  ];